# This is a basic workflow to help you get started with Actions

name: CI docker

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: docker example
        run: |
          docker build ./c# -t aimvector/csharp:1.0.0
      - name: docker build nodejs
        run: |
         docker build ./nodejs -t aimvector/nodejs:1.0.0
      - name: docker build python
        run: |
         docker build ./python -t aimvector/python:1.0.0
      - name: docker build golang
        run: |
         docker build ./golang -t aimvector/golang:1.0.0

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
